version: "3"
services:
# cloud
  rabbitmq-server:
    image: rabbitmq:management
    ports: 
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  eureka-server:
    build:  
      context: .
      dockerfile: Dockerfile
      args: 
        jarName: eureka-server
    ports: 
      - 8000:8000
  admin-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jarName: admin-server
    ports:
      - 8200:8200
#  config-server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        jarName: config-server
#    ports:
#      - 8010:8010

# apollo
  apollo-quick-start:
    build:
      context: ./deploy/apollo
    container_name: apollo-quick-start
    depends_on:
      - apollo-db
    ports:
      - 8680:8080
      - 8690:8090
      - 8670:8070
    links:
      - apollo-db

  apollo-db:
    build:
      context: ./deploy/apollo/sql
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 13306:3306

  # service
  demo-product:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jarName: product
    ports:
      - 8120:8120
  demo-order:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jarName: order
    ports:
      - 8130:8130