server:
  port: 8150

logging:
  file: apollo-demo.log

spring:
  application:
    name: Apollo-Demo
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8000/eureka/
